# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-03-29 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netName', models.CharField(max_length=50)),
                ('netDescription', models.CharField(max_length=200)),
                ('netNodeCounter', models.IntegerField()),
                ('netEdgeCounter', models.IntegerField()),
                ('netClusterCoefficient', models.FloatField()),
                ('netAverageDegree', models.FloatField()),
                ('netAveragePath', models.FloatField()),
            ],
        ),
    ]
