# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-05 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1)),
                ('directed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nodeName', models.CharField(max_length=50)),
                ('nodeId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='net',
            name='netAveragePath',
        ),
        migrations.AddField(
            model_name='net',
            name='net90EffectiveDiameter',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='net',
            name='netApproxFullDiameter',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='net',
            name='netAveragePathLength',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='net',
            name='netBiDirEdgeCounter',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='net',
            name='netClosedTriangleCounter',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='net',
            name='netConnectedComponentSize',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='net',
            name='netDirectedEdgeCounter',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='net',
            name='netFracOfClosedTriads',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='net',
            name='netOpenTriangleCounter',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='net',
            name='netSelfEdgeCounter',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='net',
            name='netStrongConnCompSize',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='net',
            name='netUndirectedEdgeCounter',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='net',
            name='netAverageDegree',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='net',
            name='netClusterCoefficient',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='net',
            name='netEdgeCounter',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='net',
            name='netNodeCounter',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='node',
            name='net',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analysis.Net'),
        ),
        migrations.AddField(
            model_name='node',
            name='node',
            field=models.ManyToManyField(related_name='neighbor', through='Analysis.Edge', to='Analysis.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='nodeIn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inEdge', to='Analysis.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='nodeOut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outEdge', to='Analysis.Node'),
        ),
    ]
