# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-05 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0002_auto_20160405_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='net',
            name='netClusterCoefficientDistribution',
            field=models.ImageField(default='D:\\temp\\SocialNetWork\\image\\default.jpg', upload_to=b''),
        ),
        migrations.AddField(
            model_name='net',
            name='netDegreeDistribution',
            field=models.ImageField(default='D:\\temp\\SocialNetWork\\image\\default.jpg', upload_to=b''),
        ),
    ]
